export enum INJECTION_TYPES {
  TOAST = "INJECTION_TYPES_TOAST",
  BACKGROUND_BLUR = "INJECTION_TYPES_BACKGROUND_BLUR",
  CHAT_FORMAT = "INJECTION_TYPES_CHAT_FORMAT",
  CASE_FORMAT = "INJECTION_TYPES_CASE_FORMAT",
  SHARE_FORMAT = "INJECTION_TYPES_SHARE_FORMAT",
}
