export enum INJECTION_TYPES {
  TOAST = "INJECTION_TYPES_TOAST",
  BACKGROUND_BLUR = "INJECTION_TYPES_BACKGROUND_BLUR",
  CHAT_FORMAT = "INJECTION_TYPES_CHAT_FORMAT",
  CASE_FORMAT = "INJECTION_TYPES_CASE_FORMAT",
  SHARE_FORMAT = "INJECTION_TYPES_SHARE_FORMAT",
  PARTICIPANT_SEARCH = "INJECTION_TYPES_PARTICIPANT_SEARCH",
  WEBSOCKET_CONNECTION = "INJECTION_TYPES_WEBSOCKET_CONNECTION",
  DATA_TABLE = "INJECTION_TYPES_DATA_TABLE",
  DATE_FORMAT = "INJECTION_TYPES_DATE_FORMAT",
  THEME_SERVICE = "THEME_SERVICE"
}
