import { Module } from "vuex";
import { RoomTemplate } from "@/model/admin/room/room-template";

const templates: {
  [key: string]: RoomTemplate;
} = {
  T1: {
    uuid: "T1",
    roomSettings: {
      template: "Funky Template",
      passcode: "YourHonor931",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Frank's Room",
      organization: "LA County Superior Court - 12345",
      status: "Available",
      phone: "555-555-5555",
      hostAccessCode: 5555,
      participantAccessCode: 5555,
    },
    organizationId: "O1",
  },
  T2: {
    uuid: "T2",
    roomSettings: {
      template: "Jazzy Template",
      passcode: "HonorYour999",
      allowPasscode: true,
      video: false,
      audio: false,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: false,
      transcription: false,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Paul's Room",
      organization: "Pierce County District Court - 59492",
      status: "Available",
      phone: "000-000-0000",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T3: {
    uuid: "T3",
    roomSettings: {
      template: "Ultimate Justice Template",
      passcode: "YourHonYour",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: false,
      handRaising: false,
      chat: false,
      recording: false,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Mikes's Room",
      organization: "Pierce County Superior Court - 59492",
      status: "Available",
      phone: "253-800-2200",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T4: {
    uuid: "T4",
    roomSettings: {
      template: "Custom Template Name",
      passcode: "passwordcodeisbad",
      allowPasscode: true,
      video: false,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "MEDIUM",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Paul's Room",
      organization: "King County Municipal Court - 59492",
      status: "Available",
      phone: "210-444-0550",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T5: {
    uuid: "T5",
    roomSettings: {
      template: "Template Ultra",
      passcode: "time49313",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: false,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: false,
      remoteTranslation: false,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Matt's Room",
      organization: "King County District Court - 59492",
      status: "Available",
      phone: "502-122-4432",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T6: {
    uuid: "T6",
    roomSettings: {
      template: "My Fair Template",
      passcode: "verygoodpasscod3",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "HIGH",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: false,
      chat: false,
      recording: false,
      emailLinkToAll: false,
      transcription: false,
      remoteTranslation: false,
      streaming: false,
      duplicateParticipantHandling: false,
    },
    roomDetails: {
      name: "Judge Mikes's Room",
      organization: "Puyallup District Court - 59492",
      status: "Available",
      phone: "620-223-0012",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T7: {
    uuid: "T7",
    roomSettings: {
      template: "Templating Isn't It",
      passcode: "codejustice2384",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "LOW",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: false,
      emailLinkToAll: false,
      transcription: false,
      remoteTranslation: false,
      streaming: false,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Jason's Room",
      organization: "Tacoma Federal Court - 59492",
      status: "Available",
      phone: "101-321-1212",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T8: {
    uuid: "T8",
    roomSettings: {
      template: "Template Time Series",
      passcode: "BigCheese3434",
      allowPasscode: true,
      video: false,
      audio: false,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "MEDIUM",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: false,
      chat: false,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Daves's Room",
      organization: "Pierce County District Court - 59492",
      status: "Available",
      phone: "321-432-4343",
      hostAccessCode: 3123,
      participantAccessCode: 3241,
    },
    organizationId: "O1",
  },
  T9: {
    uuid: "T9",
    roomSettings: {
      template: "No Template Like Template",
      passcode: "HonorJustice4553",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Paul's Room",
      organization: "Pierce County District Court - 59492",
      status: "Available",
      phone: "000-000-0000",
      hostAccessCode: 5656,
      participantAccessCode: 5656,
    },
    organizationId: "O1",
  },
  T10: {
    uuid: "T10",
    roomSettings: {
      template: "Templicious",
      passcode: "MaxHonor3434",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "LOW",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: false,
      chat: false,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Lori's Room",
      organization: "Dartmouth County Municipal Court - 59492",
      status: "Available",
      phone: "404-303-6565",
      hostAccessCode: 1202,
      participantAccessCode: 2939,
    },
    organizationId: "O1",
  },
  T11: {
    uuid: "T11",
    roomSettings: {
      template: "Wow Factor",
      passcode: "Justice4All12",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: false,
      waitingRoom: false,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: false,
      emailLinkToAll: false,
      transcription: false,
      remoteTranslation: false,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Amanda's Room",
      organization: "LA County Municipal Court - 59492",
      status: "Available",
      phone: "206-420-5301",
      hostAccessCode: 4939,
      participantAccessCode: 2341,
    },
    organizationId: "O1",
  },
  T12: {
    uuid: "T12",
    roomSettings: {
      template: "No Toggle Participants",
      passcode: "JusticeFr3312",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "HIGH",
      screenSharing: false,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: false,
      duplicateParticipantHandling: false,
    },
    roomDetails: {
      name: "Judge Mark's Room",
      organization: "LA County District Court - 59492",
      status: "Available",
      phone: "909-444-1304",
      hostAccessCode: 3674,
      participantAccessCode: 3674,
    },
    organizationId: "O1",
  },
  T13: {
    uuid: "T13",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "FreedomFree334",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: false,
      waitingRoom: false,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "LOW",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: false,
      emailLinkToAll: false,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Keith's Room",
      organization: "Reno County District Court - 59492",
      status: "Available",
      phone: "202-444-6363",
      hostAccessCode: 7249,
      participantAccessCode: 7249,
    },
    organizationId: "O1",
  },
  T14: {
    uuid: "T14",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "HonorYour999",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "MEDIUM",
      screenSharing: true,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Nate's Room",
      organization: "Reno County District Court - 59492",
      status: "Available",
      phone: "435-253-2471",
      hostAccessCode: 5379,
      participantAccessCode: 5379,
    },
    organizationId: "O1",
  },
  T15: {
    uuid: "T15",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "JudgeSup3r",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "LOW",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Bob's Room",
      organization: "LA County District Court - 59492",
      status: "Available",
      phone: "242-105-3575",
      hostAccessCode: 3579,
      participantAccessCode: 3579,
    },
    organizationId: "O1",
  },
  T16: {
    uuid: "T16",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "4th3p3opl3",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "LOW",
      screenSharing: false,
      requireScreenSharingRequest: true,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: false,
      transcription: false,
      remoteTranslation: false,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Michelle's Room",
      organization: "Tarkov County Criminal Court - 59492",
      status: "Available",
      phone: "432-101-4432",
      hostAccessCode: 7359,
      participantAccessCode: 7359,
    },
    organizationId: "O1",
  },
  T17: {
    uuid: "T17",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "freeentry2345",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "HIGH",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: true,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Tate's Room",
      organization: "King County District Court - 59492",
      status: "Available",
      phone: "431-202-2212",
      hostAccessCode: 7240,
      participantAccessCode: 7240,
    },
    organizationId: "O1",
  },
  T18: {
    uuid: "T18",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "HonorYour999",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: true,
      allowParticipantsToggleAudio: true,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: true,
      videoQuality: "HIGH",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: false,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Spock's Room",
      organization: "Federation District Court - 59492",
      status: "Available",
      phone: "432-414-5545",
      hostAccessCode: 7435,
      participantAccessCode: 7435,
    },
    organizationId: "O1",
  },
  T19: {
    uuid: "T19",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "Logstamp3424",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "MEDIUM",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Jean's Room",
      organization: "Darth County District Court - 59492",
      status: "Available",
      phone: "205-443-2347",
      hostAccessCode: 3759,
      participantAccessCode: 3759,
    },
    organizationId: "O1",
  },
  T20: {
    uuid: "T20",
    roomSettings: {
      template: "Template Name (Modified)",
      passcode: "Timewarp2408",
      allowPasscode: true,
      video: true,
      audio: true,
      allowSelectBeforeEnter: true,
      waitingRoom: true,
      audioOnlyType: "Ready To Meet",
      providerPSTN: "ZIPDX",
      allowParticipantsToggleVideo: false,
      allowParticipantsToggleAudio: false,
      defaultCanvasLayout: "Grid",
      allowParticipantsChangeLayout: false,
      videoQuality: "HIGH",
      screenSharing: false,
      requireScreenSharingRequest: false,
      fileManagement: false,
      handRaising: true,
      chat: true,
      recording: true,
      emailLinkToAll: true,
      transcription: true,
      remoteTranslation: true,
      streaming: true,
      duplicateParticipantHandling: true,
    },
    roomDetails: {
      name: "Judge Joanna's Room",
      organization: "Hoquiam County District Court - 59492",
      status: "Available",
      phone: "234-777-2345",
      hostAccessCode: 4523,
      participantAccessCode: 5356,
    },
    organizationId: "O1",
  },
};

const roomTemplateModule: Module<any, any> = {
  namespaced: true,
  state: {
    templates: templates,
  },
  mutations: {},
  actions: {},
  getters: {
    getAsList: (state) => Object.values(state.templates),
    getTemplateNamesList: (state) => {
      const templates = Object.values(state.templates) as RoomTemplate[];
      return templates.map((t: RoomTemplate) => t.roomSettings.template);
    },
  },
};

export default roomTemplateModule;
